title: Peoplepraxis
description: Helping People and Organisations Navigate Change
url: "https://www.peoplepraxis.org"
logo: "/assets/img/1.png"

defaults:
  -
    scope:
      path: ""
    values:
      custom_css: /assets/css/custom.css

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Navigation
header_pages:
  - index.md

# Trigger rebuild
